### ISSUE TITLE
Readme Twitter example

### ISSUE THREAD

**Issue by vccolombo** [ScriptSmith/socialreaper#1]
In Readme, the line
```
twt = Twitter(app_key="xxx", app_secret="xxx", oauth_token="xxx", 
    oauth_token_secret="xxx")
```

shouldn't it be:

`  twt = Twitter(api_key="xxx", api_secret="xxx", access_token="xxx", access_token_secret="xxx")`

to match apis.py implementation?

```
class Twitter(API):
    def __init__(self, api_key, api_secret, access_token, access_token_secret):
```

**Comment by ScriptSmith** [comment]
As stated in the Readme the examples only apply to socialreaper version 0.3.0 on PyPI, which uses the old naming convention.

The examples will be updated when complete documentation is written

**Comment by ScriptSmith** [comment]
As stated in the Readme the examples only apply to socialreaper version 0.3.0 on PyPI, which uses the old naming convention.

The examples will be updated when complete documentation is written

**Comment by darknodi** [comment]
@ScriptSmith Pipl Service.
